node_name: "tanderson"
server: "https://chef.llmhq.com/organizations/llmprod"
cookbook_copyright: "Lakeshore Learning Materials"
cookbook_email: "chefdevs@lakeshorelearning.com"
chef_repo_path: "repos/llmprod"