alias ls='ls -G'
alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
alias gpgreset='gpgconf --kill gpg-agent && sleep 1 && gpg2 --card-status'
alias gpgstatus='gpg2 --card-status'
alias docker-host='docker-machine ip $(docker-machine active)'
alias docker-volume-cleanup='docker volume rm $(docker volume ls -qf dangling=true)'
alias gopath='cd "$GOPATH"'
alias godevtld='cd "$DEVTLD"'
alias lakeshorechef='cd "$DEVTLD"/chef/llmhq-repo'
