source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then

    # prezto options
    zgen prezto '*:*' case-sensitive 'no'
    zgen prezto '*:*' color 'yes'
    zgen prezto prompt theme 'sorin'
    zgen prezto terminal auto-title 'yes'

    zgen prezto syntax-highlighting styles \
    'alias' 'fg=blue' \
    'builtin' 'fg=blue' \
    'command' 'fg=blue' \
    'function' 'fg=blue' \
    'precommand' 'fg=cyan' \
    'commandseparator' 'fg=green'

    # prezto and modules
    zgen prezto
    zgen prezto git
    zgen prezto history
    zgen prezto syntax-highlighting
    zgen prezto history-substring-search
    
    zgen load "${HOME}/.dotfiles/zsh/prompt.zsh"
    zgen load bhilburn/powerlevel9k powerlevel9k.zsh-theme

    if [ $(uname -a | grep -ci Darwin) = 1 ]; then
        zgen prezto homebrew
        zgen prezto osx
    fi
    
    zgen save
fi

# Source some other basic configs for zsh
source "${HOME}/.dotfiles/zsh/env.zsh"
source "${HOME}/.dotfiles/zsh/functions.zsh" 
source "${HOME}/.dotfiles/zsh/aliases.zsh"
source "${HOME}/.dotfiles/zsh/chef.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
