source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
    # prezto options
    zgen prezto '*:*' case-sensitive 'no'
    zgen prezto '*:*' color 'yes'
    zgen prezto prompt theme 'powerlevel9k'
    zgen prezto terminal auto-title 'yes'

    zgen prezto syntax-highlighting styles \
    'alias' 'fg=blue' \
    'builtin' 'fg=blue' \
    'command' 'fg=blue' \
    'function' 'fg=blue' \
    'precommand' 'fg=cyan' \
    'commandseparator' 'fg=green'

    # prezto and modules
    zgen prezto
    zgen prezto git
    zgen prezto history
    zgen prezto syntax-highlighting
    zgen prezto history-substring-search

    zgen load ${HOME}/.dotfiles/zsh/custom/
    # generate the init script from plugins above
    zgen save
fi

 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
