export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "lib/completion", from:oh-my-zsh
zplug "lib/key-bindings", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "lib/directories", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh, if:"hash git"
zplug "zsh-users/zsh-completions", from:github
zplug "zsh-users/zsh-syntax-highlighting", from:github
zplug "zchee/go-zsh-completions", from:github
zplug "esc/conda-zsh-completion", from:github
zplug "~/.zsh", from:local

zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme, as:theme


if ! zplug check --verbose; then
    printf "Install zplug plugins? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
