alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
alias gpgreset='gpgconf --kill gpg-agent && sleep 1 && gpg2 --card-status'
alias gpgstatus='gpg2 --card-status'
alias docker-volume-cleanup='docker volume rm $(docker volume ls -qf dangling=true)'
alias godevtld='cd "$DEVTLD"'
alias lakeshorechef='cd "$DEVTLD"/lakeshore/chef-repo'
alias personlchef='cd "$DEVTLD"/self/chef-repo'
alias cgcb='chef generate cookbook -b -C "$(git config --get user.name)" -m "$(git config --get user.email)"'
alias tfpersonal='_terraform_aws_profile personal'
alias tfwork='_terraform_aws_profile llmhq'
