# Make sure homebrew is first
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [[ -x /usr/local/bin/gpgconf ]]; then
  gpgconf --launch gpg-agent
  export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh
fi

# Setup for Vagrant VMware development
export VAGRANT_VMWARE_CLONE_DIRECTORY="$HOME/.vagrant.vm"
export VAGRANT_DEFAULT_PROVIDER='vmware_fusion'

